language: python

matrix:
  include:
    - python: 3.6

install:
  - pip install --upgrade pip
  - pip install --progress-bar off -r requirements.txt
  - pip install coveralls

before_script:
  - export PYTHONPATH=$PWD

script:
  - true # add other tests here
  - coveralls